### PR TITLE
get_lock() should set timeout/expiry

### PR DESCRIPTION
**Pull request by mwithheld**
Untested code

### CODE REVIEW

**Comment by mwithheld** [comment]
The CI failures are due to "Plugin "local_redislock" (2017120800) could not be installed.  It requires a newer version of Moodle".

**Comment by mwithheld** [comment]
Hi @polothy - would you be able/willing to look at the idea suggested here?

**Comment by mwithheld** [comment]
@polothy  I'm still hoping to get this lock expiry mechanism in.

**Comment by polothy** [comment]
Thanks for the contribution, but it is unlikely that we would merge this.  We [did have TTL at the start](https://github.com/blackboard-open-source/moodle-local_redislock/commit/b830943d42dac587a157bb7a7e8a2cc928627be7), but found that long running processes would have their locks expire, then we get duplicate runs going which is much worse than a stale lock for us.  For example, I don't think any scheduled task calls `extend_lock` to extend the life of their lock.  (From memory) I believe even other core locks do not use expire, but I might not be remembering that correctly or it was added after I looked.

You are more than welcome to fork or to maintain the patch yourself.  Just be careful, I believe `pexpire` is for milliseconds whereas `expire` is for seconds.

**Pull request closed without merging**
